FROM golang:1.7-wheezy

COPY . /go/src/github.com/minio/minfs-docker-volume
WORKDIR /go/src/github.com/minio/minfs-docker-volume

RUN set -ex \
    && go install --ldflags '-extldflags "-static"'

CMD ["/go/bin/minfs-docker-volume"]
